### ISSUE TITLE
create URL redirect

### ISSUE THREAD

**Issue by DeniseSl22** [cyNeo4j/DSMN#1]
From DSMN.org to https://cyneo4j.github.io/DSMN.github.io/ ? @egonw

**Comment by egonw** [comment]
Not sure what the goal is. What do you want to do?

**Comment by DeniseSl22** [comment]
Renamed the repo, we can create github.io page from a branch (that might be easier than maintaining 2 repos)

**Comment by rola-mahyob** [comment]
@DeniseSl22  hi can you help me in cyneo4j
the link url server it still false at the local host
